# Generated by Django 6.0.7 on 2026-07-25 23:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('log_text', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True)),
                ('zip_path', models.CharField(blank=True, max_length=500)),
                ('srt_path', models.CharField(blank=True, max_length=500)),
                ('params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
